# Basic
title: Yuki の Hamburg
subtitle: 每天进步一点点
welcome_message: <a href="https://github.com/chiefky" target="_blank">人生は自転車（じてんしゃ）に乗（の）るのと似（に）ている。あなたがペダルを踏（ふ）むのをやめない限（かぎ）り .</a>
description: 初心（しょしん）忘（わす）るべからず
creator: <a href="https://github.com/chiefky">@Yuki</a>

url: "https://github.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Button A, description: My Projects, url: 'https://github.com/chiefky'}
    - {title: Button B, description: A button, url: 'https://github.com/chiefky'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: Yuki_Hamburg
    github: chiefky
    mail: ky7_333@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
